#!/usr/bin/env bash
# Bash script to display specific information from /etc/passwd

while IFS=':' read -r username _ userid _ homepath _; do
    echo "Username: $username"
    echo "User ID: $userid"
    echo "Home Directory: $homepath"
done < /etc/passwd
