#!/usr/bin/env bash
# Bash script to display numbers from 1 to 20
# with special messages for specific loop iterations

counter=1

while [ $counter -le 20 ]; do
    case $counter in
        4)
            echo "$counter"
            echo "Bad luck from China"
            ;;
        9)
            echo "$counter"
            echo "Bad luck from Japan"
            ;;
        17)
            echo "$counter"
            echo "Bad luck from Italy"
            ;;
        *)
            echo $counter
            ;;
    esac

    ((counter++))
done
