#!/usr/bin/env bash
# Bash script to display time for 12 hours and 59 minutes
hour=0
while [ $hour -le 12 ]; do
    minute=1
    while [ $minute -le 59 ]; do
        echo "$hour:$minute"
        ((minute++))
    done

    ((hour++))
done | head -n 70
