#!/bin/bash

# Install ufw if not already installed
sudo apt-get install -y ufw

# Reset ufw to default settings (optional, use this if ufw is already configured)
sudo ufw reset --force

# Set the default incoming policy to deny
sudo ufw default deny incoming

# Set the default  outgoing policy to allow 
sudo ufw default allows outgoing 

# Allow SSH (port 22), HTTP (port 80), and HTTPS (port 443)
sudo ufw allow 22/tcp
sudo ufw allow 80/tcp
sudo ufw allow 443/tcp

# Add rule to redirect port 8080 to port 80
sudo ufw route allow 8080

# Enable ufw
sudo ufw --force enable

#View Status
sudo ufw status verbose
